### ISSUE TITLE
KMTech Crossover  out of production

### ISSUE THREAD

**Issue by CzarofAK** [jamesarbrown/Beolab-3500-Squeezebox#1]
Hello James, thanks a lot for your effort you put into that manual!
I have no ordered five of your panels from jlcpcb as I cant produce pcb yet.
sadly the kmtech crossover is not in production anymore. what crossover would you suggest as a replacement?
Best regards Gabriel

**Comment by jamesarbrown** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Hi,Hope its use, im going to build another soon, so i hope the documentation is all good!Not sure. If kmtech dont make i wonder if they would sell the diagrams/pcb layoutsYes i would also use jlcpcb these daysI did just look on ebay and is the attached not it?One of my disappointment was some background noise from the pi on very low volume and when you stopped the squeeze box until the pi scripts caught the stop and turned off the b+o amp. If you want to make any improvement consider that area. But its all very very tight in that casingJames                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***Sent: 9 May 2021 13:34To: ***@***.***Reply to: ***@***.***Cc: ***@***.***Subject: [jamesarbrown/Beolab-3500-Squeezebox] KMTech Crossover  out of production (#1)  
Hello James, thanks a lot for your effort you put into that manual!
I have no ordered five of your panels from jlcpcb as I cant produce pcb yet.
sadly the kmtech crossover is not in production anymore. what crossover would you suggest as a replacement?
Best regards Gabriel

**Comment by CzarofAK** [comment]
Sadly you attachement did not make it in GitHub. do you have a Link?
just got my first BEOLAB here on my table. lets see if I can disassemble it.

**Comment by jamesarbrown** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  https://www.ebay.co.uk/itm/122126121492I just google kmtech on ebay i can see the bare board and a completed board£8stg and £28stg respectively                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***Sent: 11 May 2021 22:15To: ***@***.***Reply to: ***@***.***Cc: ***@***.***; ***@***.***Subject: Re: [jamesarbrown/Beolab-3500-Squeezebox] KMTech Crossover  out of production (#1)  
Sadly you attachement did not make it in GitHub. do you have a Link?
just got my first BEOLAB here on my table. lets see if I can disassemble it.

**Comment by CzarofAK** [comment]
Unbalanced / 310Hz Crossover, correct?

**Comment by jamesarbrown** [comment]
Humm that sounds like an error. In support folder in the b+o service i am reading a crossover of 3000hz. So i would have thought i went to nearest kmtech  version

I can also not recall on balanced or unbalanced, i would need to work through that again to discover

**Comment by CzarofAK** [comment]
Well, the guy from the Ebay shop asked me, how he should configure it.
As we are using Phone jack or Cinch, it should be unbalanced. balanced are used for XLR and such.
the 310Hz i have got from the KMtech manual in the support folder, second page on the bottom.
going to read now the B&O servicemanual.

**Comment by CzarofAK** [comment]
Yes, you are right. it seems like the crossover frequency is 3000. seems also to be legit, with the size of the speakers.
Going to order it like that:
Unbalanced, 3000Hz Crossover

Ebay name of the part is:
"NEW ! LR mono 2-way active filter by KMTech BALANCED/UNBALANCED INPUT"

**Comment by jamesarbrown** [comment]
Yes I have finally found this confirming 3Khz crossover

[Wiring Diagram in This Repository](
https://raw.githubusercontent.com/jamesarbrown/Beolab-3500-Squeezebox/master/Stage5%20-%20Wiring%20Overview/images/Bang-Olufsen-Beolab_3500-Service-Manual.jpg
)

Containing
![image](https://user-images.githubusercontent.com/891438/118121656-b461eb00-b3e9-11eb-861a-a202913a18d0.png)
